### PR TITLE
don't log to google analytics when running integration tests

### LINKED ISSUE #1053: Running integration tests logs hits to google analytics
I was briefly confused about why the most visited URLs on our site are `/address_select/BB11BB/`, `/multiple_councils/DD11DD/` and so on..

### PR DESCRIPTION
**Pull request by chris48s**
Closes #1053

### CODE REVIEW

**Comment by symroe** [comment]
Happy with this, but just a thought: it is worth only having one condition in the template (`{% if not disable_ga %}`) and then doing `DISABLE_GA = DEBUG` in the same way as `TEMPLATE_DEBUG` does in core Django?

**Comment by chris48s** [comment]
`aloe_django` (or something in that stack) automatically sets `DEBUG=False` off as part of the test bootstrap, which is a sensible thing to do for an end-to-end test but its not very explicit that it does it.. I'm struggling to find an explicit reference to it in the docs (`aloe_django` is a bit thin on docs - its kind of obliquely mentioned in passing here http://aloe.readthedocs.io/projects/aloe-django/en/latest/porting.html ) but that's why I had to do [this](https://github.com/DemocracyClub/UK-Polling-Stations/blob/master/polling_stations/apps/data_finder/features/index.py#L23-L27) in the integration tests when we switched to pipleined storage.

**Comment by symroe** [comment]
Right, so the line in `testing.py` stays the same, but the template code gets a little simpler/explicit.

**Comment by chris48s** [comment]
I think it stands as it is:
* If `DEBUG=True` (i.e: we're developing locally), we don't want to log to GA
* If `DEBUG=False` and `DISABLE_GA=True` (i.e: we're running an integration test), we don't want to log to GA

**Comment by symroe** [comment]
👍

**Pull request merged**
