### PR TITLE
Consume Election Explainers data from Every Election

### PR DESCRIPTION
**Pull request by chris48s**
This PR goes hand-in-hand with https://github.com/DemocracyClub/EveryElection/pull/28 It is designed such that if EE is not returning explainers, it won't fall over but it is still probably worth co-ordinating the two. If I make changes to one they may need to be reflected in the other. I'll leave it WIP pending review of https://github.com/DemocracyClub/EveryElection/pull/28

A couple of notes/questions:
1. I've chosen to only show the explainers card when:
    * Polling station is found
    * Brand is DemocracyClub (i.e: not in the embedded version)
      Are these the correct decisions?
2. Here's an example of what the output might look like for an area with multiple elections if `get_explanations()` were to return

```
[
"""
### County Council Elections

On 4 May 2017 you will elect your county councillor in a [first past the post](http://www.parliament.uk/about/how/elections-and-voting/voting-systems/) election. Your county council is responsible for services across the whole county, including:

* education
* transport
* planning
* fire and public safety
* social care
* libraries
* waste management
* trading standards

Separately your local authority is responsible for services delivered at a local level, including:

* rubbish collection
* recycling
* Council Tax collections
* housing
* planning applications
Your local councillors are elected in separate elections.
""",

"""
### Combined Authority Mayoral Elections

On 4 May 2017 you will elect a regional mayor in a [supplementary vote](http://www.parliament.uk/about/how/elections-and-voting/voting-systems/) election. Read more about [combined authority mayors](http://www.local.gov.uk/devolution/directly-elected-mayors).
"""
]
```

screenshot at 2017-04-15 23 05 27

Obviously there's still some work we would like to do on the actual explainer text (outside scope of this PR), but does the layout, placement, etc seem ok?

Once we get something we're happy with here, we can look at doing something similar on WCIVF where this content is equally relevant.

### CODE REVIEW

**Comment by JoeMitchell** [comment]
Looks very cool! Gradually collapsing the difference between Where and Who
and What and How :D

I wonder if the different elections should be on different cards?

**Comment by chris48s** [comment]
Yeah, so here's a few other alternative layouts I tried (and discarded):

### Inception cards
screenshot at 2017-04-16 11 33 01

### Different cards, no title

(maybe the title is not needed)

screenshot at 2017-04-16 11 33 59

### Different cards, disconnected title
screenshot at 2017-04-16 11 35 08

I think we should go with either the original layout proposed in the PR (i.e: one card titled "Elections in your area" with the details of all/any applicable elections on a single card) or the "different cards, no title" layout. I don't really like the other 2. The reason I've come down on the side of putting all relevant explainers on a single card is because I think it is very slightly clearer on mobile devices (where there is a lot of vertical scrolling) that there's more than one explanation to read.. but it is a very subjective thing. If you guys prefer multiple cards, I don't have strong views on it.

One other thing to consider is that there are *some* areas where we will need to show >1 explainers but in most areas we only need to show one. Our layout needs to make sense in both cases.

**Comment by JoeMitchell** [comment]
Ooh, nice, I personally prefer Inception cards (!) — this is what was in my head when I made my earlier comment — but maybe share in the Slack and see what people think? Or I can put on the blog today?

**Comment by chris48s** [comment]
`0f68462` does the same thing as #722. If we merge #722 first, this will need rebasing to resolve MC. If we end up merging this one first, we can just close #722 as it becomes pointless

**Comment by chris48s** [comment]
rebased to resolve conflict

**Comment by symroe** [comment]
Lovely stuff – as for the card layout, let's deploy and get wider feedback, it's not the hard part of this change :)

**Pull request merged**
