### PR TITLE
Website QA

### PR DESCRIPTION
**Pull request by chris48s**
OK, so I've spent this morning really tearing apart the front-end markup and javascript with a HTML validator and JSHint. I've also run through the core user journeys:

* home -> postcode view
* home -> we don't know where you should vote
* home -> address select view -> address view

in the following browsers:

* Firefox
* Chrome (Windows)
* Chrome (Android phone)
* Microsoft Edge (Windows 10)
* IE 11 (Windows 10)
* IE 10 (Windows 7)
* IE 9 (Windows 7)
* IE 8 (Windows 7)

and just for a laugh..
* IE 6 (Windows XP)

I've not tried it in Safari on OSX or iOS though. Can someone else give that a bash?

I was expecting to suggest that we add something like
```
<!--[if lt IE 10]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser.<br />Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
```
but I was actually really surprised at how well the site works even in really old versions of IE (although I wasn't looking for small niggly issues in those browsers - just "does it roughly work").

Back to IE 9 everything seems to work (and look) totally fine for those core paths through the system. In IE 8 the styling starts to look a bit ropey, but it downgrades relatively gracefully and the map still works. In IE 6 (is anyone really still using this?), the map doesn't work and the site looks stylistically terrible, but everything is roughly in the right places and you can put a postcode in and get a polling station address or council details out of it.

I've proposed some edits to the markup and javascript here, but it is all very minor stuff. Please don't feel that I am [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality) over silly things with this PR. I think that the fact that I've tried really hard to find problems and all the changes I've proposed are essentially trivial is evidence of what a good job you've done on producing a theme that looks great while still being really compatible/accessible across such a range of platforms! Great work on that :thumbsup:

I did find a few other things which were less trivial or clear-cut, so I've raised issues for them: #187, #188, #189

### CODE REVIEW

**Comment by JoeMitchell** [comment]
Nice. I've played with Safari and all seems good on those same user
journeys.

Did make me realise we probably need an About, Privacy, Terms at some
point. (I'm not sure what the legal requirements are). Probably a cookies
thing (i wouldn't bother, but since WGovt are sponsoring). Should I make
these issues and write some copy?

And if you put a postcode that's not recognised you get a Whoops! message,
which should probably be "We are sorry, we did not recognise this postcode.
Please try again / Please test your postcode via Postcode Finder
<http://www.royalmail.com/find-a-postcode>."

**Comment by JoeMitchell** [comment]
Oh one small thing. On Chrome on Android, I get this on the address
selection... (It's fine if I tap the box, but it's not obvious that there's
anything there)

**Comment by chris48s** [comment]
Cheers for having a look, Joe.

An about/FAQ/privacy policy/terms and conditions page is probably a good idea. IMO a sentence or 2 about cookies on there is probably sufficient. There is already an about page at http://pollingstations.democracyclub.org.uk/about which you could use as a base to start from - it just isn't linked anywhere (obvious).

Whoops for invalid postcode is already logged as issue #103
UX improvement on address select for android users is logged as #189

**Comment by JoeMitchell** [comment]
Thanks Chris, you're all over it!

**Comment by symroe** [comment]
Thanks for the thorough testing, Chris!

**Pull request merged**
