### PR TITLE
Import script for Ceredigion

### LINKED ISSUE #157: Import W06000008-Ceredigion

### PR DESCRIPTION
**Pull request by chris48s**
Notes:

* There are 375 addresses which map to polling station 1071, which doesn't exist in the polling stations file supplied.

* Ceredigion has a lot of houses on seemingly un-named roads (not that unusual in rural Wales). AddressBase is very heavily oriented towards accuracy/lack of ambiguity, rather than human-readable-ness so there's quite a lot of very verbose street names which probably aren't actually used by people. For example, I doubt many people locally refer to this road: https://www.google.co.uk/maps/place/Garregwen+St,+Adpar,+Newcastle+Emlyn,+Ceredigion+SA38+9QW/@52.043854,-4.4673366,16.75z/data=!4m2!3m1!1s0x486f23bf41fac6e9:0x3ca4369d15957b49
by the name "U5218 FROM THE JUNCTION OF THE B4571 NORTH OF ADPAR TO THE JUNCTION OF THE B4333 AT RHIW FOREST". AddressBase has these names in the same column as more regular street names like "LLOYD TERRACE" or "LEWIS TERRACE", so they're fairly tricky to exclude.

* Postcodes in Ceredigion can cover quite large areas (as with Denbighshire and many other rural areas), so using the postcode centroid for the start point of directions isn't terribly accurate. In situations like this where we actually have a point for every address, it would probably be useful to add the ability to use it - but that can be improved later. Lets just get the data in there for now..

* AddressBase is fun - really fun ;)

Closes #157

### CODE REVIEW

**Comment by JoeMitchell** [comment]
Cheers Chris! Great work. Shall I get on the case with Ceredigion re 1071?

**Comment by chris48s** [comment]
Yeah - if you don't mind. It sounds like they're fairly enthusiastic so hopefully they'll be able to help

**Comment by JoeMitchell** [comment]
Hi Chris - they emailed this morning: All the electors for 1071 and 1072 go
to the polling station in 1070 – Victoria Hall, Lampeter


Ta!

**Comment by chris48s** [comment]
Cheers Joe. I'll update the PR tonight

**Comment by chris48s** [comment]
sorted

**Comment by JoeMitchell** [comment]
Woot! Smashed it.

**Pull request merged**
