### PR TITLE
Import script for Kingston Upon Thames (2022-05-05) (closes #4590)

### LINKED ISSUE #4590: Import KTT-Royal Borough of Kingston Upon Thames for 2022-05-05
EMS: Democracy Counts
Files:
- `KTT/2022-05-05/2022-04-08T10:23:22.521537/RBK_Polling Districs.csv`
- `KTT/2022-05-05/2022-04-08T10:23:22.521537/RBK_Polling Stations.csv`

### PR DESCRIPTION
**Pull request by polling-bot-4000**
PR triggered by upload at https://github.com/DemocracyClub/UK-Polling-Stations/issues/4590

### CODE REVIEW

**Comment by alexdutton** [comment]
I've rebased this PR onto a more recent master and applied black to it.

Now leaving as it was previously imported from GitHub.

**Comment by alexdutton** [comment]
This seems to have two issues: #4590 and #4591.

**Comment by GeoWill** [comment]
They aren't updating the open data. So this one is good to work on

**Comment by GeoWill** [comment]
Polling bot nailed this one :grin:

**Pull request merged**
